### PR TITLE
[Enhancement] Changing the validate button in TextArea and Upload blocks to only be shown if the user has written something or sent a file, respectively

### PR DESCRIPTION
**Pull request by JooLuiz**
#### What does this PR do? \*

Changes the validate button in Upload and TextArea blocks to appear only if the user has written something or sent a file.

#### How to test it? \*

Open Quick order and check the text area and upload components before and after adding data to it.

#### Describe alternatives you've considered, if any. \*

None

#### Related to / Depends on \*

None

### CODE REVIEW

**Comment by JooLuiz** [comment]
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [X]  Patch (backwards-compatible bug fixes)
> * [ ]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞

**Comment by JooLuiz** [comment]
> Beep boop 🤖
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
> * [X]  There's nothing new to document 🤔
> * [ ]  I'll do it later 😞
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
> * [ ]  I just updated 🎉🎉

**Comment by JooLuiz** [comment]
hi @wender 
I've noticed that there is now two more bots.
They are saying that the PR has an error, but doesn't say where or what to do to solve it.
Could you please help me understand these issues? Or is the code okei?

**Comment by JooLuiz** [comment]
Hi @wender, could you please review my pull request?

**Comment by whc105** [comment]
Please resolve the lint issues.
See here for those issues: https://github.com/vtex-apps/quickorder/runs/5132158307?check_suite_focus=true

**Review by whc105 — APPROVED** [review]

**Pull request merged**
