### PR TITLE
feat: set default value true for alwaysShowAddToCart

### PR DESCRIPTION
**Pull request by Rudge**
#### What does this PR do? \*
Set alwaysShowAddToCart with the default value of true.

#changingTooling

#### How to test it? \*

- Open the quickorder page.
- Upload the order file with nonexistent sku and existent sku.
- It shows the button "add to cart".

Screen Recording 2023-08-24 at 18 54 31

### CODE REVIEW

**Review by mairatma — COMMENTED** [review]
If I understand this is changing the default for this flag, so it'll change the behavior for everyone from now on. May that cause confusion or problems for some use cases, making them assume there are no errors and follow through by mistake?

If this is a product decision made by the team that's fine, I'm just worried in case this is because of few clients complaining, since they could start setting this flag to true individually instead of us changing the default for everyone at once.

**Comment by mairatma** [comment]
Also, there build mentions that there's a test failing on Cypress. It's in another repo, [here](https://github.com/vtex-apps/cy-runner/blob/9f0c3c67b26a8cf11a9e3423cb394b2d039de507/cypress-shared/support/quick-order/testcase.js#L328). It specifically guarantees that this button won't show up when there are invalid skus, so that again makes me worry about changing this default value, since this option was created on purpose.

**Comment by Rudge** [comment]
> If I understand this is changing the default for this flag, so it'll change the behavior for everyone from now on. May that cause confusion or problems for some use cases, making them assume there are no errors and follow through by mistake?
> 
> If this is a product decision made by the team that's fine, I'm just worried in case this is because of few clients complaining, since they could start setting this flag to true individually instead of us changing the default for everyone at once.

It is, indeed. It is a KI that has been opened by one customer, and the adjustments have been requested by Fernando.

**Comment by Rudge** [comment]
> Also, I'm curious, is this app from the B2B Suite? I didn't know about it.

The app was [reported as B2B](https://www.notion.so/vtexhandbook/Our-Apps-302048904695451d98c5a9822fc06ca0?pvs=4), but I don't know if it is just for B2B Suite.

**Comment by fobarros** [comment]
The issue is that today if the product is not found, all the items he would like to quote for are unavailable.
In fact, I believe that the best opinion is to leave it `true` and we can even analyze if someone came back with this option because it doesn't seem to make sense to me. Later I would remove this option and always treat it this way.

**Review by mairatma — DISMISSED** [review]
Awesome, thanks for clarifying!

**Comment by fobarros** [comment]
The issue is that today if the product is not found, all the items he would like to quote for are unavailable.
In fact, I believe that the best opinion is to leave it true and we can even analyze if someone came back with this option because it doesn't seem to make sense to me. Later I would remove this option and always treat it this way.
I also asked Wender why we have that and this msg error. _He said: many people have already used the quick order, I remember that it showed line by line which was invalid_

**Review by mairatma — APPROVED** [review]

**Pull request merged**
